server:
  port: 9004
spring:
  application:
    name: tensquare_article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.128:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.110.130
    port: 6379
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:6868/eureka
  ## redis key
  total:
    like:
      count:
        key: TOTAL:LIKE:COUNT
  user:
    like:
      article:
        key: USER:LIKE:ARTICLE
  article:
    liked:
      user:
        key: ARTICLE:LIKED:USER

